### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by eindiainfohub** [epsagon/lambda-cost-calculator#6]
PS C:\Users\Jack\Desktop\Project\Yannick\test1\lambda-cost-calculator> python lambda_cost_calculator.py
N/A% (0 of 20) |                                                                 | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "C:\Users\Jack\Desktop\Project\Yannick\test1\lambda-cost-calculator\lambda_cost_calculator.py", line 248, in <module>
    print_lambda_cost(arguments)
  File "C:\Users\Jack\Desktop\Project\Yannick\test1\lambda-cost-calculator\lambda_cost_calculator.py", line 131, in print_lambda_cost
    response = lambda_client.list_functions()
  File "C:\Python39\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python39\lib\site-packages\botocore\client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListFunctions operation: The security token included in the request is invalid.

**Comment by eindiainfohub** [comment]
python lambda_cost_calculator.py --token-key-id <access_key_id> --token-secret <secret_access_key>



same error with this command also.

**Comment by gonzariosm** [comment]
I had the same issue, this is because probably the token can read one region, so you can add `--regions us-east-1` to run the scan just in that region
